### ISSUE TITLE
PermissionError: [Errno 13] Permission Denied: 'files\\data.trpfs'

### ISSUE THREAD

**Issue by CantWeAllDisagree** [psthrn42/SCVI_Extract#10]
Dumped Scarlett Romfs, Moved data.trpfs folder and data.trpfd to files, put flatc.exe and the oo2core_6_win64.dll into tools

Run python script and get this error, no output folder is created. 

Extracting data from trpfs file...
Traceback (most recent call last):
  File "trpfs_extract.py", line 84, in <module>
    ExtractFS()
  File "trpfs_extract.py", line 29, in ExtractFS
    with open(file_dir + "\data.trpfs", mode="rb") as fs, open(file_dir + "\\fs_data_separated.trpfs", mode="wb") as fs_sep:
PermissionError: [Errno 13] Permission denied: 'files\\data.trpfs'

**Comment by ItsaGlitch1** [comment]
if your data.trpfd is a folder containing files like 00 and 01, you need to combine those files into one and rename it to data.trpfd.
